version: '3'
services:

  # PostgreSQL database, with GIS extension.
  db:
    image: mdillon/postgis
    container_name: postgres-server
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data_volume:/var/lib/postgresql/data

  # Django Python API.
  server:
    build:
      context: ./server/
    container_name: django-server
    restart: always
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=postgres-server

      - DJANGO_PORT=${DJANGO_PORT}
      - DJANGO_ADMIN=${DJANGO_ADMIN}
      - DJANGO_PASSWORD=${DJANGO_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

      - DJANGO_DEBUG=${DJANGO_DEBUG}
    depends_on:
      - db

  # ReactJS front-end website.
  client:
    build: 
      context: ./client/
      dockerfile: ${FRONTEND_DOCKERFILE}
    image: client:latest
    restart: always
    ports:
      - "${FRONTEND_INTERNAL_PORT}:${FRONTEND_PORT}"
    depends_on:
      - server

volumes:
  data_volume:
