version: '3'

services:
  client:
    build: 
      context: ./client/
    image: client:latest
    command: "npm start"
  db:
    image: postgres
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Pa55word
      POSTGRES_USER: friendly
      POSTGRES_DB: perioddignitydb
  server:
    build:
      context: ./server/
    command: python ./server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
